### ISSUE TITLE
pvlib has an unexpected error

### ISSUE THREAD

**Issue by Ludee** [htw-pv3/pvlib-python-pv3#130]
> Traceback (most recent call last):
  File "D:/JetBrains/PyCharm-Community-2023.1.2/plugins/python-ce/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\JetBrains\PyCharm-Community-2023.1.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "B:\git\github\htw-pv3\pvlib-python-pv3\pv3_main.py", line 94, in <module>
    run_modelchain(mc_fred, df_fred_pvlib)
  File "B:\git\github\htw-pv3\pvlib-python-pv3\pv3_sonnja_pvlib.py", line 264, in run_modelchain
    mc.run_model(weather=weather_data)
  File "D:\Anaconda3\envs\d_py38_pv3vis\lib\site-packages\pvlib\modelchain.py", line 1815, in run_model
    self._run_from_effective_irrad(weather)
  File "D:\Anaconda3\envs\d_py38_pv3vis\lib\site-packages\pvlib\modelchain.py", line 1903, in _run_from_effective_irrad
    self.dc_model()
  File "D:\Anaconda3\envs\d_py38_pv3vis\lib\site-packages\pvlib\modelchain.py", line 794, in cec
    return self._singlediode(self.system.calcparams_cec)
  File "D:\Anaconda3\envs\d_py38_pv3vis\lib\site-packages\pvlib\modelchain.py", line 776, in _singlediode
    self.results.dc = tuple(itertools.starmap(
  File "D:\Anaconda3\envs\d_py38_pv3vis\lib\site-packages\pvlib\pvsystem.py", line 943, in singlediode
    return singlediode(photocurrent, saturation_current,
  File "D:\Anaconda3\envs\d_py38_pv3vis\lib\site-packages\pvlib\pvsystem.py", line 2847, in singlediode
    out = _singlediode._lambertw(
  File "D:\Anaconda3\envs\d_py38_pv3vis\lib\site-packages\pvlib\singlediode.py", line 651, in _lambertw
    p_mp, v_mp = _golden_sect_DataFrame(params, 0., v_oc * 1.14,
  File "D:\Anaconda3\envs\d_py38_pv3vis\lib\site-packages\pvlib\tools.py", line 345, in _golden_sect_DataFrame
    raise ValueError('upper >= lower is required')
ValueError: upper >= lower is required

**Comment by jon554** [comment]
PvLib documentation of `V0.9.4` (Bugfixes):
https://pvlib-python.readthedocs.io/en/stable/whatsnew.html?highlight=_golden_sect_DataFrame#id2

**Comment by Ludee** [comment]
The workaround is a downgrade to a working version:
`pip install --upgrade pvlib==0.9.0`
